export const paths = {
  home: "/",
  topic: "/:topicSlug",
  detail: "/detail/:slug",
  search: "/tim-kiem/",
  test: "/test",
  notFound: "/404s",
  education:'/education',
  policy:'/policy',
  local:'/local',
  trainingAdmission:'/trainingAdmission',
  fourDirections:'/fourDirections',
  movement:'/movement',
  news:'/news',
  urbanEducation:'/urbanEducation',
  society:'/society',
  politics:'/politics',
  economy:'/economy',
  legalEducation: '/legal-education',
  security: '/security',
  legalSystem: '/legal-system',
  readersInvestigation: '/readers-investigation',
  connection: '/connection',
  laborUnion: '/labor-union',
  companion: '/companion',
  scienceTechnology: '/science-technology',
  exchange: '/exchange',
  methodology: '/methodology',
  expertCorner: '/expert-corner',
  school: '/school',
  skills: '/skills',
  studyAbroad: '/study-abroad',
  faces: '/faces',
  physical: '/physical',
  humanity: '/humanity',
  world: '/world',
  nationalDefenseEducation: '/national-defense-education',
  worldIssues: '/world-issues',
  strangeStories: '/strange-stories',
  health: '/health',
  healthBeauty: '/health-beauty',
  family: '/family',
  covid19Prevention: '/covid19-prevention',
  media: '/media',
  infographic: '/infographic',
  video: '/video',
  hotNews: '/hot-news',
  highlights: '/highlights',
  culture: '/culture',
  creation: '/creation',
  culturalLife: '/cultural-life',
  celebrities: '/celebrities',
  sports: '/sports',
  schoolSports: '/school-sports'
};
