export const cities = [
  { name: 'Hồ Chí Minh', value: 'Ho Chi Minh' },
  { name: 'Hà Nội', value: 'Ha Noi' },
  { name: 'Đà Nẵng', value: 'Da Nang' },
  { name: 'Huế', value: 'Hue' },
  { name: 'Cần Thơ', value: 'Can Tho' },
  { name: 'Tây Ninh', value: 'Tay Ninh' },
  { name: 'Nha Trang', value: 'Nha Trang' },
  { name: 'Vũng Tàu', value: 'Vung Tau' },
  { name: 'Phan Thiết', value: 'Phan Thiet' },
  { name: 'Buôn Ma Thuột', value: 'Buon Ma Thuot' },
  { name: 'Lâm Đồng', value: 'Lam Dong' },
  { name: 'An Giang', value: 'An Giang' },
  { name: 'Bà Rịa - Vũng Tàu', value: 'Ba Ria - Vung Tau' },
  { name: 'Bắc Giang', value: 'Bac Giang' },
  { name: 'Bắc Kạn', value: 'Bac Kan' },
  { name: 'Bạc Liêu', value: 'Bac Lieu' },
  { name: 'Bắc Ninh', value: 'Bac Ninh' },
  { name: 'Bến Tre', value: 'Ben Tre' },
  { name: 'Bình Định', value: 'Binh Dinh' },
  { name: 'Bình Dương', value: 'Binh Duong' },
  { name: 'Bình Phước', value: 'Binh Phuoc' },
  { name: 'Bình Thuận', value: 'Binh Thuan' },
  { name: 'Cà Mau', value: 'Ca Mau' },
  { name: 'Cao Bằng', value: 'Cao Bang' },
  { name: 'Đắk Lắk', value: 'Dak Lak' },
  { name: 'Đắk Nông', value: 'Dak Nong' },
  { name: 'Điện Biên', value: 'Dien Bien' },
  { name: 'Đồng Nai', value: 'Dong Nai' },
  { name: 'Đồng Tháp', value: 'Dong Thap' },
  { name: 'Gia Lai', value: 'Gia Lai' },
  { name: 'Hà Giang', value: 'Ha Giang' },
  { name: 'Hà Nam', value: 'Ha Nam' },
  { name: 'Hà Tĩnh', value: 'Ha Tinh' },
  { name: 'Hải Dương', value: 'Hai Duong' },
  { name: 'Hải Phòng', value: 'Hai Phong' },
  { name: 'Hậu Giang', value: 'Hau Giang' },
  { name: 'Hòa Bình', value: 'Hoa Binh' },
  { name: 'Hưng Yên', value: 'Hung Yen' },
  { name: 'Khánh Hòa', value: 'Khanh Hoa' },
  { name: 'Kiên Giang', value: 'Kien Giang' },
  { name: 'Kon Tum', value: 'Kon Tum' },
  { name: 'Lai Châu', value: 'Lai Chau' },
  { name: 'Lạng Sơn', value: 'Lang Son' },
  { name: 'Lào Cai', value: 'Lao Cai' },
  { name: 'Long An', value: 'Long An' },
  { name: 'Nam Định', value: 'Nam Dinh' },
  { name: 'Nghệ An', value: 'Nghe An' },
  { name: 'Ninh Bình', value: 'Ninh Binh' },
  { name: 'Ninh Thuận', value: 'Ninh Thuan' },
  { name: 'Phú Thọ', value: 'Phu Tho' },
  { name: 'Phú Yên', value: 'Phu Yen' },
  { name: 'Quảng Bình', value: 'Quang Binh' },
  { name: 'Quảng Nam', value: 'Quang Nam' },
  { name: 'Quảng Ngãi', value: 'Quang Ngai' },
  { name: 'Quảng Ninh', value: 'Quang Ninh' },
  { name: 'Quảng Trị', value: 'Quang Tri' },
  { name: 'Sóc Trăng', value: 'Soc Trang' },
  { name: 'Sơn La', value: 'Son La' },
  { name: 'Tây Ninh', value: 'Tay Ninh' },
  { name: 'Thái Bình', value: 'Thai Binh' },
  { name: 'Thái Nguyên', value: 'Thai Nguyen' },
  { name: 'Thanh Hóa', value: 'Thanh Hoa' },
  { name: 'Thừa Thiên Huế', value: 'Thua Thien Hue' },
  { name: 'Tiền Giang', value: 'Tien Giang' },
  { name: 'Trà Vinh', value: 'Tra Vinh' },
  { name: 'Tuyên Quang', value: 'Tuyen Quang' },
  { name: 'Vĩnh Long', value: 'Vinh Long' },
  { name: 'Vĩnh Phúc', value: 'Vinh Phuc' },
  { name: 'Yên Bái', value: 'Yen Bai' }
]